"""Add Event table for tracking app events

Revision ID: ae0d134607f9
Revises: 4cfe424ef7b3
Create Date: 2026-02-07 17:15:59.572067

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from app_logger import ModuleLogger


# revision identifiers, used by Alembic.
revision: str = "ae0d134607f9"
down_revision: Union[str, None] = "4cfe424ef7b3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

logger = ModuleLogger("AlembicMigrations")


def upgrade() -> None:
    # Disable foreign keys temporarily for migrations
    op.execute("PRAGMA foreign_keys=OFF")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "event",
        sa.Column(
            "event_type",
            sa.Enum(
                "MEDIA_ADDED",
                "MONITOR_CHANGED",
                "YOUTUBE_ID_CHANGED",
                "TRAILER_DOWNLOADED",
                "TRAILER_DELETED",
                "DOWNLOAD_SKIPPED",
                name="eventtype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum("USER", "SYSTEM", name="eventsource", native_enum=False),
            server_default=sa.text("'user'"),
            nullable=False,
        ),
        sa.Column(
            "source_detail",
            sa.String(),
            server_default=sa.text("('')"),
            nullable=False,
        ),
        sa.Column(
            "old_value", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column(
            "new_value", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("media_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["media_id"],
            ["media.id"],
            name=op.f("fk_event_media_id_media"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("event_pkc")),
    )
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_event_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_event_event_type"), ["event_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_event_media_id"), ["media_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_event_source"), ["source"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_event_source_detail"),
            ["source_detail"],
            unique=False,
        )

    # ### end Alembic commands ###

    # Re-enable foreign keys after migrations
    op.execute("PRAGMA foreign_keys=ON")


def downgrade() -> None:
    # Disable foreign keys temporarily for migrations
    op.execute("PRAGMA foreign_keys=OFF")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_event_source_detail"))
        batch_op.drop_index(batch_op.f("ix_event_source"))
        batch_op.drop_index(batch_op.f("ix_event_media_id"))
        batch_op.drop_index(batch_op.f("ix_event_event_type"))
        batch_op.drop_index(batch_op.f("ix_event_created_at"))

    op.drop_table("event")
    # ### end Alembic commands ###

    # Re-enable foreign keys after migrations
    op.execute("PRAGMA foreign_keys=ON")
